name: Compress Images

on:
  push:
    paths:
      - "assets/img_upload/*.svg"
      - "assets/img_upload/*.png"
      - "assets/img_upload/*.jpg"
      - "assets/img_upload/*.jpeg"
      - "assets/img_upload/*.gif"
      - "assets/img_upload/*.webp"

jobs:
  build:
    name: cadamsdev/image-optimizer-action
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Compress Images
        id: compress-images
        uses: cadamsdev/image-optimizer-action@v1
        with:
          github-token: ${{ secrets.SYNC_POSTS }}
