name: Image Processing

on:
  push:
    paths:
      - "assets/img_upload/**"
# Create a new folder[img_upload/] and push new images only to this folder.
# Add [.gitkeep] empty file inside [img_upload/] folder.

permissions:
  contents: write

jobs:
  process-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick
          echo "...ImageMagick installation complete."

      # Create 480 webp and convert original image to webp.
      - name: Process images with ImageMagick
        run: |
          echo "...Starting image processing..."

          for img in assets/img_upload/*.{jpg,jpeg,png,gif,webp}; do
            [ -e "$img" ] || continue

            convert "$img" -quality 80 -format webp -strip -resize 480x "assets/img_upload/$(basename "${img%.*}-480").webp"
            echo "+ Created 480px image: assets/img_upload/$(basename '${img%.*}-480').webp"

            convert "$img" -quality 80 -format webp -strip "assets/img_upload/$(basename "${img%.*}").webp"
            echo "+ Created original image in WebP format: assets/img_upload/$(basename '${img%.*}').webp"

            rm "$img"
          done
          echo "...Image processing complete."

      - name: Move files
        run: |
          mv assets/img_upload/* assets/img/

      # Insert your info.
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{secrets.SYNC_POSTS}}
        run: |
          git config --local user.name "RayCC51"
          git config --local user.email "4q26dd@gmail.com"
          git add assets/img/*
          git add assets/img_upload/*
          git commit -m "Image processed" || echo "No changes"
          git push
